version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "1313:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_PASS=testpass123
      - DB_USER=myapp
      - DB_NAME=myapp
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - myappDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myapp
    restart: always
volumes:
  myappDB:
